diff --git a/Makefile b/Makefile
--- a/Makefile
+++ b/Makefile
@@ -150,6 +150,7 @@
 	$U/_forphan\
 	$U/_dorphan\
 	$U/_sync\
+	$U/_sleep\
 
 fs.img: mkfs/mkfs README $(UPROGS)
 	mkfs/mkfs fs.img README $(UPROGS)
